// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsfctaswehaeylgpylvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzZmN0YXN3ZWhhZXlsZ3B5bHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMDU1MDcsImV4cCI6MjA1MjY4MTUwN30.uOAl3DoWVEZxI1DmhP8WDin9GoGLjW3EAwbVfbotdSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);